query = """
SELECT
PEGASUS.PESSOA.NOMEFANTASIA,
PEGASUS.PESSOA.RAZAOSOCIAL AS RAZAOSOCIAL,
PEGASUS.PESSOA.CNPJ AS A1_CGC,
PESSOA.CNAE,
ENDERECO.CEP,
PEGASUS.ENDERECO.LOGRADOURO  AS A1_END,
PEGASUS.BAIRRO.BAIRRO  AS A1_BAIRRO,
PEGASUS.ESTADO.SIGLAESTADO  AS A1_EST,
PEGASUS.CIDADE.CIDADE  AS A1_MUN,
PEGASUS.PESSOA.CELULAR AS A1_TEL,
PEGASUS.PESSOA.EMAIL AS A1_EMAIL,
VENDEDOR.RAZAOSOCIAL AS A1_VENDEDOR,
PROMOTOR.RAZAOSOCIAL AS A1_PROMOTOR,
CLASSIFICACAOPESSOA.CLASSIFICACAOPESSOA
FROM PEGASUS.PESSOACLIENTE
INNER JOIN PEGASUS.PESSOA ON PEGASUS.PESSOACLIENTE.CNPJ = PESSOA.CNPJ
LEFT JOIN PEGASUS.ENDERECO ON PEGASUS.PESSOA.CODENDERECOPRINCIPAL = PEGASUS.ENDERECO.CODENDERECO
LEFT JOIN PEGASUS.BAIRRO ON PEGASUS.ENDERECO.CODBAIRRO = PEGASUS.BAIRRO.CODBAIRRO
LEFT JOIN PEGASUS.CIDADE ON PEGASUS.BAIRRO.CODCIDADE = PEGASUS.CIDADE.CODCIDADE
LEFT JOIN PEGASUS.ESTADO ON PEGASUS.CIDADE.CODESTADO = PEGASUS.ESTADO.CODESTADO
LEFT JOIN PEGASUS.PESSOA VENDEDOR ON PEGASUS.PESSOACLIENTE.CNPJVENDEDOR = VENDEDOR.CNPJ
LEFT JOIN PEGASUS.PESSOA PROMOTOR ON PEGASUS.PESSOACLIENTE.CNPJPROMOTOR = PROMOTOR.CNPJ
LEFT JOIN PEGASUS.CLASSIFICACAOPESSOA ON PESSOA.CODCLASSIFICACAOPESSOA = PEGASUS.CLASSIFICACAOPESSOA.CODCLASSIFICACAOPESSOA
LIMIT 10
"""

